package-lock.json, src/Components/Layout/index.js, src/Components/TimeSheets/Create Button/create-button.module.css, src/Components/TimeSheets/Create Button/index.js, src/Components/TimeSheets/Delete Button/index.js, src/Components/TimeSheets/Expand Modal/expandmodal.module.css, src/Components/TimeSheets/Expand Modal/index.js, src/Components/TimeSheets/Expand button/index.js, src/Components/TimeSheets/Form/form.module.css, src/Components/TimeSheets/Form/index.js, src/Components/TimeSheets/Select/index.js, src/Components/TimeSheets/index.js, src/Components/TimeSheets/time-sheets.module.css
Screens for Timesheets resource, with the following functionalities:
- See the list of timesheets saved in the DB.
- Edit a timesheet.
- Delete a timesheet.
- Add a new timesheet.
=> BaSP-TG-44: Timesheets Screens

src/Components/Layout/index.js, src/Components/Tasks/Form/index.js, src/Components/Tasks/Modal/messageModal.js, src/Components/Tasks/Modal/taskModal.js, src/Components/Tasks/Modal/tasks.module.css, src/Components/Tasks/index.js, src/Components/Tasks/listItem.js, src/Components/Tasks/tasks.module.css, src/Components/Tasks/tasksList.js
**List Tasks:**
• Retrieve Tasks from data base
• Created a Table view where the information is shown
• Added three buttons, to add, to delete and to edit tasks
**Delete Tasks**
• Implemented the functionality to delete a task from the list.
**Create a Task**
• Created the form view.
• Implemented the functionality to add a new task.
**Update a Task**
•  Implemented the functionality to update a task from the list.
=> BaSP-TG-45: Task entity

src/Components/Projects/Form/FormEmployees/index.js, src/Components/Projects/Form/index.js
CHANGE defaultValue prop inside the form to value
=> BaSP-TG-73: FIX Project empty inputs when EDIT

src/Components/Employees/EmployeeForm.js, src/Components/Employees/employees.module.css
New title added to the form and fixed form style.
=> BaSP-TG-74:Misalign employees form fixed

src/Components/Layout/index.js
When the route is not contemplated in react router, it sent the user back to /home
=> BaSP-TG-76: ADDED redirect to home if wrong url is sent

README.md
I added the members of this project and how we work in the first week.
=> BaSP-TG-49: Readme update

src/Components/Employees/EmployeeForm.js, src/Components/Projects/Form/FormEmployees/index.js, src/Components/Projects/Form/index.js
Fixed action for save button when creating or editing a Project or Employee.
=> BaSP-TG-105: Fix Employees and Projects save button

src/Components/Projects/Form/index.js
In the projects form, the label for 'Project Name' was changed from 'Pojec' to 'Project'
=> BaSP-TG-104: Fixed project misspelling

src/Components/Admins/editAdminForm.jsx, src/Components/Employees/EmployeeForm.js, src/Components/Projects/Form/FormEmployees/index.js, src/Components/Projects/Form/index.js, src/Components/Shared/Datepicker/index.js, src/Components/Shared/Input/input.js, src/Components/Shared/Input/input.module.css, src/Components/Shared/Select/index.js, src/Components/SuperAdmins/Form/index.js, src/Components/Tasks/Form/index.js, src/Components/TimeSheets/Form/index.js
implemented hook form shared input added it to all entities.
=> BaSP-TG-111: Shared input update

src/Components/Admins/editAdminForm.jsx, src/Components/Admins/validations.jsx
Replace the actual logic for react hook form logic
Add joi validations
=> BaSP-TG-112: Admin form update

src/Components/Tasks/Form/index.js, src/Components/Tasks/Form/validations.js
Implemented React Hook Forms and Joi libraries in Tasks Formulary.
=> BaSP-TG-117: Hook forms in Tasks

src/Components/Employees/EmployeeForm.js, src/Components/Employees/validation.js
Update the logic in the employee entity to use rect hook form and have joi validations
-  How to test:
=> BaSP-TG-114: Employee form update

src/Components/Admins/editAdminForm.jsx, src/Components/Admins/index.js, src/Components/Employees/EmployeeForm.js, src/Components/Employees/index.js, src/Components/Layout/AdminLayout/index.js, src/Components/Projects/Form/form.module.css, src/Components/Projects/Form/index.js, src/Components/Projects/index.js, src/Components/SuperAdmins/Form/index.js, src/Components/SuperAdmins/index.js, src/Components/Tasks/Form/index.js, src/Components/Tasks/index.js, src/Components/TimeSheets/Form/form.module.css, src/Components/TimeSheets/Form/index.js, src/Components/TimeSheets/index.js
Fixed the edit and create routes that were missing in the admin layout.
=> BaSP-TG-129: fix form routes for admin entity in layout

src/Components/Shared/Datepicker/datePicker.module.css, src/Components/Shared/Datepicker/index.js, src/Components/Shared/Input/input.js, src/Components/Shared/Input/input.module.css, src/Components/Shared/Select/index.js, src/Components/Shared/Select/select.module.css
Description
It was found in projects and in timesheets that messages that appear when the user enters an invalid input shows different colors
Expected results
They should all be red
textarea should be fixed in the textarea shared component ticket
=> BaSP-TG-125 All invalid input messages should be red.

src/Components/Pages/Employee/TimeSheetsList/Form/form.module.css, src/Components/Pages/Employee/TimeSheetsList/Form/index.jsx, src/Components/Projects/Form/form.module.css, src/Components/Projects/Form/index.js, src/Components/Shared/TextArea/index.jsx, src/Components/Shared/TextArea/textArea.module.css, src/Components/Tasks/Form/index.js, src/Components/TimeSheets/Form/form.module.css, src/Components/TimeSheets/Form/index.js
Created a text area shared component and replaced all text area already existing with it
=> BaSP-TG-127: Textarea shared component

src/Components/Admins/validations.jsx, src/Components/Employees/validation.js, src/Components/Projects/validations.jsx, src/Components/SuperAdmins/Form/validations.js, src/Components/Tasks/Form/validations.js, src/Components/TimeSheets/Form/validations.js
- Messages for all entities must follow the same criteria.
- In the attached file are the messages agreed by the team
=> BaSP-TG-126: Standardize error error messages

src/Components/Layout/AdminLayout/index.js, src/Components/Layout/EmployeeLayout/index.js, src/index.js
Implemented lazy loading to improve page-loading perfomance.
=> TG-110: implementent lazy loading

src/Components/Pages/Auth/SignUp/index.js, src/Components/Pages/Auth/SignUp/signup.module.css, src/Components/Pages/Auth/SignUp/validation.js, src/Routes/index.js
Page use to create a new employee.
=> BaSP-TG-134: sign up created

src/Components/Home/index.js, src/Components/Pages/Auth/Login/index.jsx, src/Components/Pages/Auth/Login/login.module.css, src/Components/Pages/Auth/Login/validations.js, src/Components/Shared/Sidebar/index.js, src/Routes/index.js, src/redux/auth/reducer.js, src/redux/auth/thunks.js
Created the sign in page with Firebase authentication 
Redirect to the role entity of the logged in user
Logout button to delete token from session storage and logout from the app
Work done by Federico Peralta, Gonzalo Asencio and Maicol Freire
=> BaSP-TG-133: Sign In Page

src/Components/Admins/editAdminForm.jsx, src/Components/Admins/index.js, src/Components/Employees/EmployeeForm.js, src/Components/Employees/index.js, src/Components/Layout/AdminLayout/index.js, src/Components/Pages/Employee/MyProfile/MyProfile.js, src/Components/Pages/Employee/MyProfile/MyProfileEdit.js, src/Components/Pages/Employee/ProjectList/index.js, src/Components/Pages/Employee/TimeSheetsList/index.jsx, src/Components/Projects/Form/index.js, src/Components/Projects/index.js, src/Components/SuperAdmins/Form/index.js, src/Components/SuperAdmins/ListSuperAdmins/index.js, src/Components/SuperAdmins/index.js, src/Components/Tasks/Form/index.js, src/Components/Tasks/index.js, src/Components/TimeSheets/Form/index.js, src/Components/TimeSheets/index.js, src/redux/admins/thunks.js, src/redux/employees/thunks.js, src/redux/projects/thunks.js, src/redux/superAdmins/thunks.js, src/redux/tasks/thunks.js, src/redux/timeSheets/thunks.js
Add Token to Headers in every request made to the server
=> BaSP-TG-139: add token header to requests

src/redux/employees/reducer.js
=> TG-163: fixed employee signup

src/Components/Admins/index.js, src/Components/Employees/index.js, src/Components/Layout/AdminLayout/index.js, src/Components/Layout/EmployeeLayout/index.js, src/Components/Layout/SuperAdminLayout/index.js, src/Components/Pages/Admin/Employees/EmployeeList/index.js, src/Components/Pages/Admin/MyProfile/index.js, src/Components/Pages/Admin/Projects/ProjectForm/index.js, src/Components/Pages/Admin/Projects/ProjectList/index.js, src/Components/Pages/Admin/TimeSheetsList/index.js, src/Components/Pages/Auth/Login/index.jsx, src/Components/Pages/Employee/MyProfile/MyProfile.js, src/Components/Pages/Employee/ProjectList/index.js, src/Components/Pages/Employee/TimeSheetsList/index.jsx, src/Components/Pages/SuperAdmin/Admins/AdminList/index.js, src/Components/Pages/SuperAdmin/MyProfile/index.js, src/Components/Projects/Form/index.js, src/Components/Projects/index.js, src/Components/Shared/Loading/index.js, src/Components/Shared/Loading/loading.module.css, src/Components/SuperAdmins/index.js, src/Components/Tasks/index.js, src/Components/TimeSheets/index.js, src/Routes/index.js
=> BaSP-TG-141: Spinner component

package-lock.json, package.json, src/Components/Pages/Admin/MyProfile/index.js, src/Components/Pages/Admin/Projects/ProjectForm/ProjectEmployees/index.js, src/Components/Pages/Employee/MyProfile/MyProfile.js, src/Components/Pages/SuperAdmin/MyProfile/index.js, src/Components/Shared/Button/Button.js, src/Components/Shared/Button/button.module.css, src/Components/Shared/Datepicker/datePicker.module.css, src/Components/Shared/Select/select.module.css, src/Components/Shared/Table/TableRow/index.js
=> BaSP-TG-168: add icons instead text
